version: '2'

services:
  
  mfaidp:
    image: silintl/ssp-base:feature_mfa
    volumes:
      - ./:/mfa
      - ./development/enable-debug.sh:/data/enable-debug.sh
      - ./development/run-dev.sh:/data/run-dev.sh
      - ./development/run-tests.sh:/data/run-tests.sh
      - ./development/symlink.sh:/data/symlink.sh
      - ./development/idp-local/UserPass.php:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php
      - ./src:/data/src

      # Revert to standard SSOService.php instead of using sildisco'saml20-idp-hosted
      - ./development/idp-local/www_saml2_idp_SSOService.php:/data/vendor/simplesamlphp/simplesamlphp/www/saml2/idp/SSOService.php

      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    
    env_file:
      - ./common.env
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=a
      - APPLICATION_ENV=test
      - IDP_NAME=Local IdP
      - MFA_SETUP_URL=https://www.google.com/
      - ID_BROKER_ACCESS_TOKEN=dummy
      - ID_BROKER_ASSERT_VALID_IP=false
      - ID_BROKER_BASE_URI=dummy
      - ID_BROKER_TRUSTED_IP_RANGES=192.168.0.1/8
      - SECRET_SALT=NOT-a-SECRET-1362102e525237994020fb7ff18753c8
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - REMEMBER_ME_SECRET=not-a-secret-570c5b18dacd45bd
      - THEME_USE=default:default
    command: /data/run-dev.sh
  
  mfasp:
    image: silintl/ssp-base:feature_mfa
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    env_file:
      - ./common.env
    environment:
      - IDP_NAME=THIS VARIABLE IS REQUIRED BUT PROBABLY NOT USED
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - THEME_USE=default:default
  
  tests:
    image: silintl/ssp-base:feature_mfa
    links:
      - mfaidp
      - mfasp
    volumes:
      - ./development/run-tests.sh:/data/run-tests.sh
      - ./composer.json:/data/composer.json
      - ./composer.lock:/data/composer.lock
      - ./features:/data/features
    env_file:
      - ./common.env
    environment:
      - MFA_SETUP_URL=https://www.google.com
      - THEME_USE=default:default
    working_dir: /data
    command: /data/run-tests.sh
